### ISSUE TITLE
add bit packing for weak USB chipset e.g. RPi so that they can operate at 10MSPS

### ISSUE THREAD

**Issue by ghost** [Guenael/airspy-wsprd#1]
Could you add a command line argument to enable bit packing (
https://i.imgur.com/qXnWoEK.png?1 ) it would be useful (ref:
http://cgit.osmocom.org/gr-osmosdr/commit/?id=164a09fc11cec2d8b15b38e8b512fa542d6cecc7
- it is one line to enable bit-packing and unpacking is handled
  transparently by libairspy, so only the data across the USB bus that is bit
  packed)

**Comment by Guenael** [comment]
I get your point. On my todo list. 
No need more than 2.5M (or 3M) to extract 375sps. But I give this option, so I will push this feature. Thanks!

**Comment by ghost** [comment]
I always try and use the maximum sample rate possible after reading this http://www.atmel.com/images/doc8003.pdf You trade bandwidth for additional dynamic range. You can't pull a signal out of nowhere but if there is enough signal (and noise) to tickle the least significant bit(s) of the ADC, then you can pull a stronger signal out of the noise.

**Comment by ghost** [comment]
The 2.5MSPS is an experimental mode and does not have as clean of a spectrum as the 10MSPS.
"Experimental 2.5MSPS IQ output for low power devices (Raspberry Pi, Odroid, etc.)" - http://airspy.com/airspy-r2/  So 10MSPS would be better.

**Comment by Guenael** [comment]
@itsbert Thx for your comment. I perfectly understand your point, but I thought a decimation was already done in hardware (and in this case, there is no advantage). But I never checked the FW code. I will add this bit packing option, and re-write the decimator to implement a CIC filter.

**Comment by Guenael** [comment]
@martinzsmith I use a RaspberryPI 2, and initially the CPU load was around 69% @2.5MHz, but now, with a simple decimator, the load was more close than 18%. So I will make tests @10MHz and check for packet loss and power consumption. Thanks!

**Comment by Guenael** [comment]
Bits packing added :
"\t-p packing: Set packing for samples, \n"
"\t   1=enabled(12bits packed), 0=disabled(default 16bits not packed)\n"

**Comment by ghost** [comment]
No decimation happens inside the the Airspy, they even underclock (Maximum MCU clockrate in the datasheet is 204 MHz ).
Mini is clocked at 144MHz or 72MHz ( https://github.com/airspy/firmware/blob/master/common/airspy_mini_conf.c#L59 ) and the 
NOS is clocked at 140MHz or 40MHz ( https://github.com/airspy/firmware/blob/master/common/airspy_nos_conf.c#L60 )

There is not enough RAM or processing power in the MCU to decimate the data.

**Comment by ghost** [comment]
Thank you.
