### ISSUE TITLE
another useful command line argument would be frequency offset

### ISSUE THREAD

**Issue by ghost** [Guenael/airspy-wsprd#3]
If you were using an up converter like the SpyVerter or ham-it-up etc., having the option to specify a frequency offset e.g 120001003 Hz or 125003003 Hz would be extremely useful.

**Comment by Guenael** [comment]
Again, thanks for your feedback!
This option exist (-p frequency correction), but having a separate option for SpyVerter could be great.
I have no SpyVerter, but in the same time, it could be useful to receive a 3 bands (ex. 7, 10 & 14 MHz) with a modified version of airspy-wsprd.

**Comment by ghost** [comment]
Sorry, I assumed that -p was ppm correction and not a frequency offset.

**Comment by bammi** [comment]
In the parseing for the p option, i changed the atoi() to atofs() so that its easier to enter the sift frequency, for example for the Spyverter as -p -120M

after the change, i am now running the command for 40M wspr (7.0386 MHz)
 ./airspy_wsprd -f 127.0386M -p -120M -r 2.5M -c KC1CCR -g FN42gn -l 12 -m 8 -v 8 -b 1
but i am getting zero decodes (i put a printf after wspr_decode to see the value of n_results)
am i thinking about this correctly?

**Comment by Guenael** [comment]
Nop, do no use "-p -120M". The receiver will try to tune 7.0386MHz, outside of the [24-1700M] range. I will add an option for spyverter, but for now, simply make the conversion yourself.
-p option should be used if you want correct a small frequency offset.

**Comment by ghost** [comment]
@bammi 

> $ ./airspy_wsprd -f 10.1387M -c censored1 -g censored2 -l 12 -m 8 -v 8 -s 0x0123456789ABCDEF -r 6M -p 119999839 -b 1
> Starting airspy-wsprd (2016-06-05, 03:15z) -- Version 0.1
>   Dial freq. : 10138700 Hz
>   Real freq. : 130138539 Hz
>   Rate       : 3000000 Hz
>   Callsign   : censored1
>   Locator    : censored2
>   LNA gain   : 10 dB
>   Mixer gain : 7 dB
>   VGA gain   : 7 dB
>   Bias       : 1
>   S/N        : 0x0123456789ABCDEF

The above works for me on a mini. I tried -120000000 the first time and failed. Then I looked at the code and saw that it tunes to the real frequency. (+sample_rate/4+1500, instead of +sample_rate/2+1500 - to avoid a non existent DC spike on an Airspy)

**Comment by bammi** [comment]
-r 6M gives me a error , incorrect value (or something to that effect). I tried -f 10.1387M -r 2.5M and -p adjusted for (sample rate/4+1500) ith noi joy, tried other wspr frequencies on 20M and 40M too, so jpy. Runniong wspr on the same antenna via my elecraft kx3/wsprx gives lots of decodes on all those bands. Will dig further ........

**Comment by ghost** [comment]
@bammi I was using an Airspy mini which has sample rates of 6MSPS and 3MSPS,  if you are using an Airspy NOS the two sample rates are 10MSPS and 2.5MSPS. 

Can you maybe give the command line you were using and the output (or exact error message) like I did above. 

-f 10.1387M on its own will not work since the Airspy can only tune between 24MHz and 1800MHz you need to use -p with an offset (for a spyverter[12000xxxx]/ham-it-up[12500xxxx]/...) to move the REAL frequency inside the range 24MHz to 1800MHz.

Is the command working and the problem is that the antenna you are using is attenuating heavily at the  frequency of interest ?

**Comment by Guenael** [comment]
@bammi @martinzsmith Thx martinzsmith, perfect answer. I would add on point. airspy-wsprd was initially designed to receive VHF and UHF bands (50, 144, 222 and 432MHz). Of course it will work on HF bands with SpyVerter and I will update the code for this, but I don't own this extension for now.
